-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/MediaUploader/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mu_campaign (
  campaign_page_id INT UNSIGNED NOT NULL,
  campaign_enabled INT DEFAULT 0 NOT NULL,
  campaign_validity INT NOT NULL,
  campaign_content LONGBLOB DEFAULT NULL,
  UNIQUE INDEX mu_campaign_page (campaign_page_id),
  INDEX mu_campaign_enabled (
    campaign_enabled, campaign_page_id
  ),
  PRIMARY KEY(campaign_page_id)
) /*$wgDBTableOptions*/;
